package main

import (
	"fmt"
	"strings"

	"github.com/nickpdawson/cairn-mdm/internal/config"
)

// renderTOML produces a readable cairn.toml reflecting the chosen options. It is
// hand-rendered (rather than struct-marshaled) so the file carries comments and
// only the sections relevant to the selected modes.
func renderTOML(cfg config.Config) string {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	w("# Cairn configuration — generated by `cairn init`.\n")
	w("# Secrets are never inlined here; use the *_file / *_env companions.\n\n")

	w("[server]\n")
	w("public_url = %q\n", cfg.Server.PublicURL)
	w("listen = %q\n", cfg.Server.Listen)
	w("mdm_path = %q\n\n", cfg.Server.MDMPath)

	w("[server.tls]\n")
	w("mode = %q\n", string(cfg.Server.TLS.Mode))
	switch cfg.Server.TLS.Mode {
	case config.TLSACME:
		w("acme_email = %q\n", cfg.Server.TLS.ACMEEmail)
	case config.TLSFiles:
		w("cert_file = %q\n", cfg.Server.TLS.CertFile)
		w("key_file = %q\n", cfg.Server.TLS.KeyFile)
	}
	w("\n")

	w("[storage]\n")
	w("driver = %q\n", string(cfg.Storage.Driver))
	w("path = %q\n\n", cfg.Storage.Path)

	w("[ca]\n")
	w("mode = %q\n", string(cfg.CA.Mode))
	switch cfg.CA.Mode {
	case config.CAImport:
		w("\n[ca.import]\n")
		w("cert_file = %q\n", cfg.CA.Import.CertFile)
		w("key_file = %q\n", cfg.CA.Import.KeyFile)
	case config.CAExternal:
		w("\n[ca.external]\n")
		w("scep_url = %q\n", cfg.CA.External.SCEPURL)
		w("ca_chain_file = %q\n", cfg.CA.External.CAChainFile)
		w("# challenge_env = \"CAIRN_SCEP_CHALLENGE\"\n")
	}
	w("\n")

	w("[log]\n")
	w("format = %q\n", cfg.Log.Format)
	w("level = %q\n", cfg.Log.Level)

	return b.String()
}
